"""Search vocabulary for query classification and LLM extraction.

Term lists serve two consumers:
- query_classifier.py: compiled into regex patterns at module level for query classification.
- anthropic_adapter.py: injected into the enrichment prompt as a canonical reference list
  so the LLM extracts standardised Traditional Chinese terms for menu_highlights and
  coffee_origins.

All terms must be lowercase — the normalizer handles case before matching (query classifier).
Changes to these lists affect both regex matching behaviour and LLM extraction output.
"""

ITEM_TERMS: list[str] = [
    # === Food (zh) ===
    "巴斯克蛋糕",
    "司康",
    "可頌",
    "肉桂捲",
    "戚風蛋糕",
    "提拉米蘇",
    "布丁",
    "鬆餅",
    "貝果",
    "三明治",
    "甜點",
    "蛋糕",
    "千層蛋糕",
    # Pastries
    "馬芬",
    "費南雪",
    "可麗露",
    "閃電泡芙",
    "泡芙",
    "丹麥麵包",
    "布里歐",
    "巧克力可頌",
    "蝴蝶酥",
    # Cakes & desserts
    "起司蛋糕",
    "巧克力蛋糕",
    "瑞士捲",
    "蒙布朗",
    "奶酪",
    "烤布蕾",
    "慕斯蛋糕",
    "磅蛋糕",
    "檸檬塔",
    # Savory
    "厚片吐司",
    "蛋沙拉",
    "法式吐司",
    "鹹派",
    # Japanese / Asian
    "和菓子",
    "大福",
    "羊羹",
    "銅鑼燒",
    "鯛魚燒",
    "麻糬",
    # Traditional Taiwanese
    "鳳梨酥",
    "蜂蜜蛋糕",
    # === Food (en) ===
    "basque cheesecake",
    "scone",
    "croissant",
    "cinnamon roll",
    "chiffon cake",
    "tiramisu",
    "pudding",
    "waffle",
    "bagel",
    "sandwich",
    "mille crepe",
    # Pastries
    "muffin",
    "financier",
    "canele",
    "eclair",
    "cream puff",
    "danish",
    "brioche",
    "pain au chocolat",
    "palmier",
    # Cakes & desserts
    "cheesecake",
    "chocolate cake",
    "swiss roll",
    "mont blanc",
    "panna cotta",
    "creme brulee",
    "mousse cake",
    "pound cake",
    "lemon tart",
    # Savory
    "thick toast",
    "egg salad toast",
    "french toast",
    "quiche",
    # Japanese / Asian
    "wagashi",
    "daifuku",
    "mochi",
    "taiyaki",
    # Traditional Taiwanese
    "pineapple cake",
    "castella",
    # === Drinks (zh) ===
    "拿鐵",
    "卡布奇諾",
    "美式",
    "摩卡",
    "抹茶",
    "可可",
    "果汁",
    "氣泡水",
    "手沖",
    "冰滴",
    "冷萃",
    "虹吸",
    "愛樂壓",
    "義式濃縮",
    # More coffee drinks
    "骯咖",
    "馥芮白",
    "燕麥拿鐵",
    "豆漿拿鐵",
    "特調",
    "濾掛",
    # Tea & non-coffee
    "抹茶拿鐵",
    "焙茶",
    "焙茶拿鐵",
    "烏龍",
    "玄米茶",
    "伯爵茶",
    "柚子茶",
    "燕麥奶",
    "豆漿",
    # === Drinks (en) ===
    "latte",
    "cappuccino",
    "espresso",
    "americano",
    "mocha",
    "matcha",
    "cold brew",
    "cold drip",
    "pour over",
    "siphon",
    "aeropress",
    "drip coffee",
    # More coffee drinks
    "dirty coffee",
    "flat white",
    "oat milk latte",
    "drip bag",
    # Tea & non-coffee
    "matcha latte",
    "hojicha",
    "hojicha latte",
    "oolong",
    "earl grey",
    "yuzu tea",
    "oat milk",
    "soy milk",
    # === Dietary modifiers (zh) ===
    "無麩質",
    "素食",
    "純素",
    "低糖",
    "無糖",
    "無乳糖",
    # === Dietary modifiers (en) ===
    "gluten-free",
    "vegetarian",
    "vegan",
    "sugar-free",
    "lactose-free",
]

SPECIALTY_TERMS: list[str] = [
    # === Origins — countries (zh) ===
    "耶加雪菲",
    "藝伎",
    "衣索比亞",
    "肯亞",
    "哥倫比亞",
    "巴拿馬",
    "瓜地馬拉",
    "盧安達",
    "蘇門答臘",
    "哥斯大黎加",
    # Additional producing countries
    "巴西",
    "薩爾瓦多",
    "宏都拉斯",
    "尼加拉瓜",
    "玻利維亞",
    "秘魯",
    "厄瓜多",
    "蒲隆地",
    "坦尚尼亞",
    "印尼",
    "蘇拉威西",
    "烏干達",
    # === Origins — countries (en) ===
    "yirgacheffe",
    "geisha",
    "gesha",
    "ethiopia",
    "kenya",
    "colombia",
    "panama",
    "guatemala",
    "rwanda",
    "sumatra",
    "costa rica",
    # Additional producing countries
    "brazil",
    "el salvador",
    "honduras",
    "nicaragua",
    "bolivia",
    "peru",
    "ecuador",
    "burundi",
    "tanzania",
    "indonesia",
    "sulawesi",
    "uganda",
    # === Sub-origins — Ethiopia (zh) ===
    "西達摩",
    "古吉",
    "哈拉爾",
    "金瑪",
    "柯契爾",
    # === Sub-origins — Ethiopia (en) ===
    "sidama",
    "sidamo",
    "guji",
    "harrar",
    "harar",
    "jimma",
    "kochere",
    # === Sub-origins — Kenya (zh) ===
    "涅里",
    "奇里尼亞加",
    # === Sub-origins — Kenya (en) ===
    "nyeri",
    "kirinyaga",
    # === Sub-origins — Colombia (zh) ===
    "惠蘭",
    "納里尼奧",
    "考卡",
    # === Sub-origins — Colombia (en) ===
    "huila",
    "nariño",
    "cauca",
    "antioquia",
    "tolima",
    # === Sub-origins — Guatemala (zh) ===
    "安地瓜",
    "薇薇特南果",
    # === Sub-origins — Guatemala (en) ===
    "antigua",
    "huehuetenango",
    "acatenango",
    # === Sub-origins — Panama (zh) ===
    "波奎特",
    # === Sub-origins — Panama (en) ===
    "boquete",
    "volcan",
    # === Sub-origins — Indonesia (zh) ===
    "曼特寧",
    "黃金曼特寧",
    "加悠",
    "托拉加",
    "爪哇",
    "佛羅勒斯",
    # === Sub-origins — Indonesia (en) ===
    "mandheling",
    "golden mandheling",
    "gayo",
    "toraja",
    "java",
    "flores",
    # === Sub-origins — Rwanda & Burundi (zh) ===
    "卡揚薩",
    "恩戈齊",
    # === Sub-origins — Rwanda & Burundi (en) ===
    "kayanza",
    "ngozi",
    "nyamasheke",
    "huye mountain",
    # === Other notable origins (zh) ===
    "藍山",
    "科納",
    "阿里山",
    # === Other notable origins (en) ===
    "blue mountain",
    "kona",
    "alishan",
    # === Varieties & cultivars (zh) ===
    "瑰夏",
    "藝妓",
    "波旁",
    "鐵比卡",
    "卡杜拉",
    "帕卡馬拉",
    "象豆",
    "原生種",
    "花魁",
    # === Varieties & cultivars (en) ===
    "bourbon",
    "typica",
    "caturra",
    "catuai",
    "pacamara",
    "maragogype",
    "sl28",
    "sl34",
    "heirloom",
    "pink bourbon",
    "wush wush",
    "sudan rume",
    "74110",
    "74158",
    # === Processing (zh) ===
    "日曬",
    "日曬處理",
    "水洗",
    "水洗處理",
    "蜜處理",
    "蜜製",
    "黃蜜",
    "紅蜜",
    "黑蜜",
    "厭氧",
    "厭氧發酵",
    "厭氧日曬",
    "厭氧水洗",
    "碳酸浸漬",
    "溼剝法",
    "乳酸發酵",
    "紅酒處理",
    "實驗性處理法",
    # === Processing (en) ===
    "natural process",
    "natural",
    "dry process",
    "washed process",
    "washed",
    "fully washed",
    "honey process",
    "honey processed",
    "yellow honey",
    "red honey",
    "black honey",
    "white honey",
    "anaerobic",
    "anaerobic fermentation",
    "anaerobic natural",
    "anaerobic washed",
    "carbonic maceration",
    "wet hulled",
    "giling basah",
    "lactic fermentation",
    "wine process",
    "experimental processing",
    # === Roast & style (zh) ===
    "單品",
    "淺焙",
    "淺烘焙",
    "中焙",
    "中烘焙",
    "中深焙",
    "深焙",
    "深烘焙",
    "北歐烘焙",
    "自家烘焙",
    "自烘",
    "精品咖啡",
    "莊園豆",
    "競標豆",
    # === Roast & style (en) ===
    "single origin",
    "light roast",
    "light roasted",
    "medium roast",
    "medium roasted",
    "medium dark roast",
    "dark roast",
    "dark roasted",
    "nordic roast",
    "self roasted",
    "house roasted",
    "in-house roast",
    "omni roast",
    "specialty coffee",
    "estate coffee",
    "competition lot",
]
