// Declares CSS side-effect imports so tsc resolves them without next-env.d.ts
// (which is gitignored and only generated by `pnpm dev` / `pnpm build`).
declare module '*.css';
declare module 'mapbox-gl/dist/mapbox-gl.css';
